@echo off
REM GitHub Issues Creation Script for Instagram Automation SaaS
REM Run this script after authenticating with: gh auth login
REM 
REM Phase 1 (Issues #1-7) - MVP Development
echo Creating Phase 1 issues...

echo Creating Issue #1: Project Setup and Infrastructure...
gh issue create --title "[Phase1] プロジェクトセットアップとインフラ構築" --body "## 概要%%0Aプロジェクトの初期セットアップとAWSインフラ構築を行う。%%0A%%0A## タスク%%0A%%0A### タスク1-1: リポジトリとCI/CDパイプライン構築%%0A- [ ] サブタスク1-1-1: GitHubリポジトリ作成%%0A  - [ ] プライベートリポジトリ作成%%0A  - [ ] ブランチ戦略（main, develop, feature/*）設定%%0A  - [ ] プルリクエストテンプレート作成%%0A%%0A- [ ] サブタスク1-1-2: GitHub Actions CI/CD設定%%0A  - [ ] Lintチェックフロー実装%%0A  - [ ] ユニットテスト実行フロー実装%%0A  - [ ] E2Eテスト実行フロー実装%%0A  - [ ] デプロイフロー実装%%0A%%0A- [ ] サブタスク1-1-3: コード品質ツール導入%%0A  - [ ] ESLint設定%%0A  - [ ] Prettier設定%%0A  - [ ] husky/pre-commit hook設定%%0A%%0A### タスク1-2: クラウドインフラ構築（AWS）%%0A- [ ] サブタスク1-2-1: AWSアカウント設定%%0A  - [ ] VPC作成%%0A  - [ ] サブネット構成（パブリック、プライベート）%%0A  - [ ] セキュリティグループ作成%%0A%%0A- [ ] サブタスク1-2-2: データベース設定%%0A  - [ ] Amazon RDS (PostgreSQL) 作成%%0A  - [ ] Amazon ElastiCache (Redis) 作成%%0A  - [ ] 接続設定%%0A%%0A- [ ] サブタスク1-2-3: デプロイ環境構築%%0A  - [ ] ECSクラスター作成%%0A  - [ ] Fargateタスク定義作成%%0A  - [ ] ALB (Application Load Balancer) 設定%%0A%%0A- [ ] サブタスク1-2-4: ドメイン・SSL証明書設定%%0A  - [ ] Route 53でドメイン登録%%0A  - [ ] ACMでSSL証明書発行%%0A  - [ ] DNS設定" --label "phase1,infrastructure,backend,frontend"

echo Creating Issue #2: Authentication and User Management...
gh issue create --title "[Phase1] 認証・ユーザー管理機能開発" --body "## 概要%%0Aユーザー登録・認証およびInstagramアカウント連携機能を開発する。%%0A%%0A## タスク%%0A%%0A### タスク2-1: ユーザー登録・認証機能%%0A- [ ] サブタスク2-1-1: ユーザー登録API開発%%0A  - [ ] メールアドレス・パスワード受付%%0A  - [ ] バリデーション実装%%0A  - [ ] メール認証送信%%0A%%0A- [ ] サブタスク2-1-2: 認証API開発%%0A  - [ ] JWTトークン発行%%0A  - [ ] リフレッシュトークン対応%%0A  - [ ] ログアウト処理%%0A%%0A- [ ] サブタスク2-1-3: パスワード管理機能%%0A  - [ ] パスワードリマインダー%%0A  - [ ] パスワード変更%%0A  - [ ] BCryptハッシュ化実装%%0A%%0A### タスク2-2: Instagramアカウント連携機能%%0A- [ ] サブタスク2-2-1: OAuth連携実装%%0A  - [ ] Meta Facebook SDK導入%%0A  - [ ] OAuthフロー実装%%0A  - [ ] アクセストークン取得・保存%%0A%%0A- [ ] サブタスク2-2-2: トークン管理機能%%0A  - [ ] トークンの自動更新%%0A  - [ ] 有効期限チェック%%0A  - [ ] 再認証フロー%%0A%%0A### タスク2-3: ユーザー管理UI開発%%0A- [ ] サブタスク2-3-1: ログイン画面%%0A  - [ ] メール/パスワード入力フォーム%%0A  - [ ] SNS連携ボタン（Google）%%0A  - [ ] レスポンシブデザイン%%0A%%0A- [ ] サブタスク2-3-2: ダッシュボード画面（ベース）%%0A  - [ ] ナビゲーション%%0A  - [ ] ユーザー情報表示%%0A  - [ ] Instagram連携状態表示" --label "phase1,backend,frontend,authentication"

echo Creating Issue #3: Instagram Graph API Integration...
gh issue create --title "[Phase1] Instagram Graph API連携" --body "## 概要%%0AInstagram Graph APIとの連携基盤を構築する。%%0A%%0A## タスク%%0A%%0A### タスク3-1: APIクライアントライブラリ構築%%0A- [ ] サブタスク3-1-1: Instagram Graph API SDK導入%%0A  - [ ] 公式SDK検証・選定%%0A  - [ ] 認証ミドルウェア実装%%0A  - [ ] レート制限ハンドラー実装%%0A%%0A- [ ] サブタスク3-1-2: APIラッパーモジュール作成%%0A  - [ ] エンドポイント抽象化%%0A  - [ ] エラーハンドリング%%0A  - [ ] 再試行ロジック%%0A%%0A### タスク3-2: Webhook受信機能%%0A- [ ] サブタスク3-2-1: Webhookエンドポイント実装%%0A  - [ ] コメントイベント受信%%0A  - [ ] DMイベント受信%%0A  - [ ] シグネチャ検証%%0A%%0A- [ ] サブタスク3-2-2: イベント処理キュー%%0A  - [ ] メッセージキュー導入%%0A  - [ ] 非同期処理実装%%0A  - [ ] 再試行機能" --label "phase1,backend,api,instagram"

echo Creating Issue #4: DM Bulk Sending Feature...
gh issue create --title "[Phase1] DM一斉配信機能開発" --body "## 概要%%0ADM（ダイレクトメッセージ）の一斉配信機能を開発する。%%0A%%0A## タスク%%0A%%0A### タスク4-1: 配信管理機能%%0A- [ ] サブタスク4-1-1: キャンペーン管理API%%0A  - [ ] 作成・取得・削除%%0A  - [ ] ステータス管理（draft, scheduled, sending, completed）%%0A  - [ ] 配信履歴%%0A%%0A- [ ] サブタスク4-1-2: セグメント機能%%0A  - [ ] セグメント作成・編集%%0A  - [ ] 条件設定（AND/OR）%%0A  - [ ] 動的更新%%0A%%0A### タスク4-2: 配信実行エンジン%%0A- [ ] サブタスク4-2-1: 一斉配信ロジック%%0A  - [ ] レート制限考慮の分散送信%%0A  - [ ] エラーハンドリング%%0A  - [ ] 進捗追跡%%0A%%0A- [ ] サブタスク4-2-2: 予約配信機能%%0A  - [ ] スケジューラー実装%%0A  - [ ] cronジョブ設定%%0A  - [ ] 時間帯ルール%%0A%%0A### タスク4-3: 配信UI開発%%0A- [ ] サブタスク4-3-1: 配信作成画面%%0A  - [ ] メッセージエディタ%%0A  - [ ] 配信先選択%%0A  - [ ] プレビュー機能%%0A%%0A- [ ] サブタスク4-3-2: 配信履歴画面%%0A  - [ ] 一覧表示・フィルタ%%0A  - [ ] 詳細表示%%0A  - [ ] エクスポート機能" --label "phase1,backend,frontend,dm"

echo Creating Issue #5: Comment Auto-Reply Feature...
gh issue create --title "[Phase1] コメント自動返信機能開発" --body "## 概要%%0AInstagram投稿へのコメントを自動で返信する機能を開発する。%%0A%%0A## タスク%%0A%%0A### タスク5-1: コメント監視機能%%0A- [ ] サブタスク5-1-1: Webhook処理拡張%%0A  - [ ] コメント抽出%%0A  - [ ] スパムフィルター%%0A  - [ ] キューイング%%0A%%0A- [ ] サブタスク5-1-2: トリガー設定%%0A  - [ ] キーワード設定%%0A  - [ ] 正規表現対応%%0A  - [ ] 条件保存%%0A%%0A### タスク5-2: 返信生成機能（シンプル版）%%0A- [ ] サブタスク5-2-1: テンプレート返信%%0A  - [ ] テンプレート管理%%0A  - [ ] 変数埋め込み%%0A  - [ ] ランダム選択%%0A%%0A- [ ] サブタスク5-2-2: 返信管理%%0A  - [ ] 承認待ちキュー%%0A  - [ ] 手動承認画面%%0A  - [ ] 履歴管理%%0A%%0A### タスク5-3: コメント管理UI%%0A- [ ] サブタスク5-3-1: コメント一覧画面%%0A  - [ ] リアルタイム更新%%0A  - [ ] フィルタ機能%%0A  - [ ] 返信状態表示%%0A%%0A- [ ] サブタスク5-3-2: テンプレート管理画面%%0A  - [ ] 作成・編集・削除%%0A  - [ ] プレビュー%%0A  - [ ] カテゴリ管理" --label "phase1,backend,frontend,comment"

echo Creating Issue #6: Testing and Quality Assurance...
gh issue create --title "[Phase1] テスト・品質保証" --body "## 概要%%0Aテスト環境の構築と品質保証プロセスを確立する。%%0A%%0A## タスク%%0A%%0A### タスク6-1: ユニットテスト%%0A- [ ] サブタスク6-1-1: APIテスト実装%%0A  - [ ] Jest/Vitest設定%%0A  - [ ] モック作成%%0A  - [ ] カバレッジ80%%以上%%0A%%0A- [ ] サブタスク6-1-2: ユーティリティテスト実装%%0A  - [ ] 共通関数テスト%%0A  - [ ] エッジケース対応%%0A%%0A### タスク6-2: インテグレーションテスト%%0A- [ ] サブタスク6-2-1: API連結テスト%%0A  - [ ] Supertest/Django Test Client使用%%0A  - [ ] シナリオテスト%%0A  - [ ] データセット準備%%0A%%0A- [ ] サブタスク6-2-2: Instagram APIスタブ%%0A  - [ ] モックサーバー構築%%0A  - [ ] レスポンスパターン定義%%0A%%0A### タスク6-3: E2Eテスト%%0A- [ ] サブタスク6-3-1: Playwright/Cypress導入%%0A  - [ ] 主要フローのシナリオ%%0A  - [ ] スナップショットテスト%%0A  - [ ] CI連携%%0A%%0A- [ ] サブタスク6-3-2: ロードテスト%%0A  - [ ] k6/Locust導入%%0A  - [ ] 同時ユーザー1,000%%0A  - [ ] ボトルネック特定" --label "phase1,backend,frontend,testing"

echo Creating Issue #7: MVP Release Preparation...
gh issue create --title "[Phase1] MVPリリース準備" --body "## 概要%%0AMVPリリースに向けた最終準備を行う。%%0A%%0A## タスク%%0A%%0A### タスク7-1: ドキュメント作成%%0A- [ ] サブタスク7-1-1: ユーザーマニュアル%%0A  - [ ] チュートリアル作成%%0A  - [ ] FAQ作成%%0A  - [ ] トラブルシューティング%%0A%%0A- [ ] サブタスク7-1-2: APIドキュメント%%0A  - [ ] Swagger/OpenAPI定義%%0A  - [ ] エンドポイント仕様%%0A  - [ ] エラーコード一覧%%0A%%0A### タスク7-2: セキュリティチェック%%0A- [ ] サブタスク7-2-1: 脆弱性スキャン%%0A  - [ ] OWASP ZAP実行%%0A  - [ ] 依存パッケージAudit%%0A  - [ ] 脆弱性修正%%0A%%0A- [ ] サブタスク7-2-2: ペネトレーションテスト%%0A  - [ ] SQLインジェクション%%0A  - [ ] XSS%%0A  - [ ] CSRF%%0A%%0A### タスク7-3: リリース%%0A- [ ] サブタスク7-3-1: 本番デプロイ%%0A  - [ ] ブルーグリーンデプロイ%%0A  - [ ] ヘルスチェック%%0A  - [ ] ロールバック計画%%0A%%0A- [ ] サブタスク7-3-2: パフォーマンス確認%%0A  - [ ] 監視設定確認%%0A  - [ ] エラーレート監視%%0A  - [ ] ユーザーフィードバック収集" --label "phase1,infrastructure,documentation,security"

echo Phase 1 issues created!
